name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: scp -r -o StrictHostKeyChecking=no ./* ubuntu@${{ secrets.EC2_PUBLIC_DNS }}:/home/ubuntu/backend

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_DNS }} << 'EOF'
            cd /home/ubuntu/backend
            sudo docker-compose down
            sudo docker-compose up --build -d
          EOF
